language: node_js
node_js:
  - "6"
env:
  - TEST_DIR=jasmine
  - TEST_DIR=karma-jasmine
  - TEST_DIR=karma-mocha
  - TEST_DIR=mocha
  - TEST_DIR=protractor
before_script:
  # Needed for Protractor
  - export DISPLAY=:99.0
script:
  - cd $TEST_DIR && npm install && npm test
