language: node_js
node_js:
  - "6"
env:
  - TEST_DIR=jasmine
  - TEST_DIR=karma-jasmine
  - TEST_DIR=karma-mocha
  - TEST_DIR=mocha
  # - TEST_DIR=protractor
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - node_modules/.bin/webdriver-manager update --standalone --firefox'
#   - node_modules/.bin/webdriver-manager start 2>&1 &
#   - sleep 5
script: cd $TEST_DIR && npm install && npm test
